<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-us">
<head>
   <meta http-equiv="content-type" content="text/html; charset=utf-8" />
   <title>excecoes</title>
   <meta name="author" content="" />

   <!--- Blueprint CSS Framework -->
   <link rel="stylesheet" href="css/blueprint/screen.css" type="text/css" media="screen, projection">
   <link rel="stylesheet" href="css/blueprint/print.css" type="text/css" media="print">
   <!--[if IE]>
      <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection">
   <![endif]-->

   <!-- CodeRay syntax highlighting CSS -->
   <link rel="stylesheet" href="css/coderay.css" type="text/css" />

   <!-- Homepage CSS -->
   <link rel="stylesheet" href="css/site.css" type="text/css" media="screen, projection" />
</head>
<body>

<div class="container">

   <div class="column span-20 prepend-2 append-2 first last" id="header">
     <p class="title">Tutorial de Ruby do GURU-SP</p>
     <hr>
   </div>

   <div class="column span-15 prepend-2 first">
      <p class="title">excecoes</p>
<h2>Raising An Exception</h2>
<p>An exception is a special kind of object, an instance of the class Exception or a descendant of that class that represents some kind of exceptional condition; it indicates that something has gone wrong. When this occurs, an exception is raised (or thrown). By default, Ruby programs terminate when an exception occurs. But it is possible to declare exception handlers. An exception handler is a block of code that is executed if an exception occurs during the execution of some other block of code. Raising an exception means stopping normal execution of the program and transferring the flow-of-control to the exception handling code where you either deal with the problem that&#8217;s been encountered or exit the program completely. Which of these happens &#8211; dealing with it or aborting the program &#8211; depends on whether you have provided a rescue clause (rescue is a fundamental part of the Ruby language). If you haven&#8217;t provided such a clause, the program terminates; if you have, control flows to the rescue clause.</p>
<p>Ruby has some predefined classes &#8211; Exception and its children &#8211; that help you to handle errors that can occur in your program. The following figure shows the Ruby exception hierarchy.</p>

			<ol>
				<li>INCLUIR IMAGEM AQUI! (Exception Hierarchy) ########</li>
			</ol><p>Reference: The above figure is from the Programming Ruby book.</p>
<p>The chart above shows that most of the subclasses extend a class known as StandardError. These are the &#8220;normal&#8221; exceptions that typical Ruby programs try to handle. The other exceptions represent lower-level, more serious, or less recoverable conditions, and normal Ruby programs do not typically attempt to handle them.</p>
<p>The following method raises an exception whenever it&#8217;s called. Its second message will never be printed. Program p043raise.rb</p>
<p><code class='ruby'></p>
<ol>
	<li>p043raise.rb<br />
  def raise_exception<br />
    puts &#8216;I am before the raise.&#8217;<br />
    raise &#8216;An error has occured&#8217;<br />
    puts &#8216;I am after the raise&#8217;<br />
  end<br />
  raise_exception<br />
</code></li>
</ol>
<p>The output is:</p>
<p><code class='bash'>
  &gt;ruby p043raise.rb
  I am before the raise.
  p043raise.rb:4:in `raise_exception': An error has occured (RuntimeError)
      from p043raise.rb:7
  &gt;Exit code: 1
</code></p>
<p>The raise method is from the Kernel module. By default, raise creates an exception of the RuntimeError class. To raise an exception of a specific class, you can pass in the class name as an argument to raise. Refer program p044inverse.rb</p>
<p><code class='ruby'></p>
<ol>
	<li>p044inverse.rb<br />
  def inverse(x)<br />
    raise ArgumentError, &#8216;Argument is not numeric&#8217; unless x.is_a? Numeric<br />
    1.0 / x<br />
  end<br />
  puts inverse(2)<br />
  puts inverse(&#8216;not a number&#8217;)<br />
</code></li>
</ol>
<p>The output is:</p>
<p><code class='bash'>
  &gt;ruby p044inverse.rb
  0.5
  p044inverse.rb:3:in `inverse': Argument is not numeric (ArgumentError)
      from p044inverse.rb:7
  &gt;Exit code: 1
</code></p>
<p>Remember, methods that act as queries are often named with a trailing ?. is_a? is a method in the Object class and returns true or false. The unless modifier when tacked at the end of a normal statement means execute the preceding expression unless condition is true.</p>
<p>Defining new exception classes: To be even more specific about an error, you can define your own Exception subclass:</p>
<p><code class='ruby'>
  class NotInvertibleError &lt; StandardError
  end
</code></p>
<h2>Handling an Exception</h2>
<p>To do exception handling, we enclose the code that could raise an exception in a begin-end block and use one or more rescue clauses to tell Ruby the types of exceptions we want to handle. It is to be noted that the body of a method definition is an implicit begin-end block; the begin is omitted, and the entire body of the method is subject to exception handling, ending with the end of the method.</p>
<p>The program p045handexcp.rb illustrates this:</p>
<p><code class='ruby'></p>
<ol>
	<li>p045handexcp.rb<br />
  def raise_and_rescue<br />
    begin<br />
      puts &#8216;I am before the raise.&#8217;<br />
      raise &#8216;An error has occured.&#8217;<br />
      puts &#8216;I am after the raise.&#8217;<br />
    rescue<br />
      puts &#8216;I am rescued.&#8217;<br />
    end<br />
    puts &#8216;I am after the begin block.&#8217;<br />
  end<br />
  raise_and_rescue<br />
</code></li>
</ol>
<p>The output is:</p>
<p><code class='bash'>
  &gt;ruby p045handexcp.rb
  I am before the raise.
  I am rescued.
  I am after the begin block.
  &gt;Exit code: 0
</code></p>
<p>Observe that the code interrupted by the exception never gets run. Once the exception is handled, execution continues immediately after the begin block that spawned it.</p>
<p>If you write a rescue clause with no parameter list, the parameter defaults to StandardError. Each rescue clause can specify multiple exceptions to catch. At the end of each rescue clause you can give Ruby the name of a local variable to receive the matched exception. The parameters to the rescue clause can also be arbitrary expressions (including method calls) that return an Exception class. If we use raise with no parameters, it re-raises the exception.</p>
<p>You can stack rescue clauses in a begin/rescue block. Exceptions not handled by one rescue clause will trickle down to the next:</p>
<p><code class='ruby'>
  begin</p>
<ol>
	<li>-<br />
  rescue OneTypeOfException</li>
	<li>-<br />
  rescue AnotherTypeOfException</li>
	<li>-<br />
  else</li>
	<li>Other exceptions<br />
  end<br />
</code></li>
</ol>
<p>For each rescue clause in the begin block, Ruby compares the raised Exception against each of the parameters in turn. The match will succeed if the exception named in the rescue clause is the same as the type of the currently thrown exception, or is a superclass of that exception. The code in an else clause is executed if the code in the body of the begin statement runs to completion without exceptions. If an exception occurs, then the else clause will obviously not be executed. The use of an else clause is not particularly common in Ruby.</p>
<p>If you want to interrogate a rescued exception, you can map the Exception object to a variable within the rescue clause, as shown in the program p046excpvar.rb</p>
<p><code class='ruby'></p>
<ol>
	<li>p046excpvar.rb<br />
  begin<br />
    raise &#8216;A test exception.&#8217;<br />
  rescue Exception =&gt; e<br />
    puts e.message<br />
    puts e.backtrace.inspect<br />
  end<br />
</code></li>
</ol>
<p>The output is:</p>
<p><code class='bash'>
  &gt;ruby p046excpvar.rb
  A test exception.
  ["p046excpvar.rb:3"]
  &gt;Exit code: 0
</code></p>
<p>The Exception class defines two methods that return details about the exception. The message method returns a string that may provide human-readable details about what went wrong. The other important method is backtrace. This method returns an array of strings that represent the call stack at the point that the exception was raised.</p>
<p>If you need the guarantee that some processing is done at the end of a block of code, regardless of whether an exception was raised then the ensure clause can be used. ensure goes after the last rescue clause and contains a chunk of code that will always be executed as the block terminates. The ensure block will always run.</p>
<p>Some common exceptions are:</p>
<p>RuntimeError (this is the default exception raised by the raise method), NoMethodError, NameError, IOError, TypeError and ArgumentError.</p>
<p>An Example: Let&#8217;s modify program p027readwrite.rb to include exception handling as shown in example p046xreadwrite.rb below.</p>
<p><code class='ruby'></p>
<ol>
	<li>p046xreadwrite.rb</li>
	<li>Open and read from a text file</li>
	<li>Note that since a block is given, file will automatically be closed when the block terminates<br />
  begin<br />
    File.open(&#8216;p014constructs.rb&#8217;, &#8216;r&#8217;) do |f1|<br />
      while line = f1.gets<br />
        puts line<br />
      end<br />
    end</li>
</ol>
<ol>
	<li>Create a new file and write to it<br />
    File.open(&#8216;test.rb&#8217;, &#8216;w&#8217;) do |f2|</li>
	<li>use &quot;&quot; for two lines of text<br />
      f2.puts &#8220;Created by Satish\nThank God!&#8221;<br />
    end<br />
  rescue Exception =&gt; msg</li>
	<li>display the system generated error message<br />
    puts msg<br />
  end<br />
</code></li>
</ol>
<div class='box'>
<p>Improper error messages can provide critical information about an application which may aid an attacker in exploiting the application. The most common problem occurs when detailed internal error messages such as stack traces, database dumps, and error codes are displayed to the user. Security analysts view logging and error handling as potential areas of risk. It is recommended that production applications should not use, for example, a puts e.backtrace.inspect call unless it is being directly committed into a log that is not viewable to the end user.</p>
</div>
<h2>Validation example</h2>
<p>Here&#8217;s an example from the Ruby Cookbook, showing how one can do validation of user&#8217;s inputs.</p>
<p><code class='ruby'>
  class Name</p>
<ol>
	<li>Define default getter methods, but not setter methods.<br />
    attr_reader :first, :last</li>
	<li>When someone tries to set a first name, enforce rules about it.<br />
    def first=(first)<br />
      if first == nil or first.size == 0<br />
        raise ArgumentError.new(&#8216;Everyone must have a first name.&#8217;)<br />
      end<br />
      first = first.dup<br />
      first<sup class="footnote"><a href="#fn0">0</a></sup> = first<sup class="footnote"><a href="#fn0">0</a></sup>.chr.capitalize<br />
      @first = first<br />
    end</li>
</ol>
<ol>
	<li>When someone tries to set a last name, enforce rules about it.<br />
    def last=(last)<br />
      if last == nil or last.size == 0<br />
        raise ArgumentError.new(&#8216;Everyone must have a last name.&#8217;)<br />
      end<br />
      @last = last<br />
    end</li>
</ol>
def full_name
&#8220;#{@first} #{@last}&#8221;
end
<ol>
	<li>Delegate to the setter methods instead of setting the instance</li>
	<li>variables directly.<br />
    def initialize(first, last)<br />
      self.first = first<br />
      self.last = last<br />
    end<br />
  end</li>
</ol>
jacob = Name.new(&#8216;Jacob&#8217;, &#8216;Berendes&#8217;)
jacob.first = &#8216;Mary Sue&#8217;
jacob.full_name # =&gt; &#8220;Mary Sue Berendes&#8221;
john = Name.new(&#8216;john&#8217;, &#8216;von Neumann&#8217;)
john.full_name # =&gt; &#8220;John von Neumann&#8221;
john.first = &#8216;john&#8217;
john.first # =&gt; &#8220;John&#8221;
john.first = nil
<ol>
	<li>ArgumentError: Everyone must have a first name.<br />
  Name.new(&#8216;Kero, international football star and performance artist&#8217;, nil)</li>
	<li>ArgumentError: Everyone must have a last name.<br />
</code></li>
</ol>
<p>The Name class keeps track of peoples&#8217; first and last names. It uses setter methods to enforce two somewhat parochial rules: everyone must have both a first and a last name, and everyone&#8217;s first name must begin with a capital letter. The Name class has been written in such a way, that the rules are enforced both in the constructor and after the object has been created. Sometimes you don&#8217;t trust the data coming in through the setter methods. That&#8217;s when you can define your own methods to stop bad data before it infects your objects. Within a class, you have direct access to the instance variables. You can simply assign to an instance variable and the setter method won&#8217;t be triggered. If you do want to trigger the setter method, you&#8217;ll have to call it explicitly. Note how, in the Name#initialize method above, we call the first= and last= methods instead of assigning to @first and @last. This makes sure the validation code gets run for the initial values of every Name object. We can&#8217;t just say first = first, because first is a variable name in that method.</p>
   </div>

   <div class="column span-5 append-2 last">

      <p><a href="http://www.guru-sp.org" title="Grupo de Usuários Ruby de SP"><img src="images/logo_guru-sp.jpg" title="Logo do GURU-SP" alt="Logo do Guru-SP" /></a></p>

      <div class="box">
         <p>Este material tem como base o <a href="http://www.rubylearning.com" title="Ruby Learning">tutorial do RubyLearning.com de Satish Talim</a> e foi traduzido por membros do <a href="http://www.guru-sp.org" title="Grupo de Usuários Ruby de SP">GURU-SP</a> com a permissão do autor.</p>
        <p class="last">Ajude o RubyLearning participando em algum dos <a href="http://www.rubylearning.org" title="cursos do Ruby Learning">cursos pagos</a> ou <a href="http://pledgie.com/campaigns/415" title="Ajude o Ruby Learning">fazendo uma doação para o projeto</a></p>
      </div>

      <p class="quiet"><a href="index.html" title="índice">Voltar para o índice</a></p>

      <h5></h5>
      <p class="incr"></p>
   </div>

   <div class="column span-20 prepend-2 append-2 first last" id="footer">
     <hr />
     <p>Tuturial de Ruby do <a href="http://www.guru-sp.org" title="Grupo de Usuários Ruby de SP">GURU-SP</a>. Este site foi criado com <a href="http://webby.rubyforge.org">Webby</a></p>
   </div>

</div>
</body>
</html>
